server:
  port: 7777
spring:
  profiles:
    default: native
  cloud:
    config:
      server:
        native:
          search-locations: [
              classpath:/configs/apiserver,
              classpath:/configs/pubserver
          ]

